//@dart=2.9
class Massignmentfromdetails {
  int id;
  String assignments_id;
  String status;
  String registeras;
  int time_from;
  int time_to;
  String start_date;
  String end_date;
  int client_id;
  String client_name;
  int department_id;
  String department_name;
  int employee_id;
  String employee_name;
  String employee_fname;
  String created_at;
  String updated_at;
  String type;
  String education_title;
  num payrate;
  String description;
  String requirements;
  String conditions;
  String extra_description;
  String speedasignment;
  String surchargeassignment;
  String sleepshift;
  String invoice;
  String Registeras ;
  num client_payrate;
  String  agreementtext;
  String 	agreement_id;
  String sleeptime;
  String preagreementtext;
  String breake;
  String year;
  String month;
  String  day;
  String comment;
  int employee_id1;
  int employee_id2;
  int employee_id3;
  int employee_id4;
  int employee_id5;
  int employee_id6;
  int employee_id7;
  int employee_id8;
  int employee_id9;
  int employee_id10;
  String times_status;
  String times_id;
  String beforeinvoice_id;
  String admin_id;
  String caninsertassignment;
  String totalpayrate;
  String totalclientpayrate;
  String duration;
  String clientfirstname;
  String clientlastname;
  String title;
  String emfirstname;
  String emlastname;
  String maintime_from;
  String maintime_to;
  String company_name;
  String total;
  String temptotalpayrate;
  String temptotalclientpayrate;
  String temptotal;

  Massignmentfromdetails.fromJson(Map<String , dynamic> parsedJson)
  {
    id = parsedJson['id'];
    assignments_id = parsedJson['assignments_id'];
    time_from = parsedJson['time_from'];
    time_to = parsedJson['time_to'];
    start_date = parsedJson['start_date'];
    end_date = parsedJson['end_date'];
    client_id = parsedJson['client_id'];
    client_name = parsedJson['client_name'];
    department_id = parsedJson['department_id'];
    department_name = parsedJson['department_name'];
    employee_id = parsedJson['employee_id'];
    employee_name = parsedJson['employee_name'];
    employee_fname = parsedJson['employee_fname'];
    created_at = parsedJson['created_at'];
    updated_at = parsedJson['updated_at'];
    registeras = parsedJson['registeras'];
    status = parsedJson['status'];
    caninsertassignment = parsedJson['caninsertassignment'];
    education_title  = parsedJson['education_title'];
    payrate  = parsedJson['payrate'];
    description  = parsedJson['description'];
    requirements  = parsedJson['requirements'];
    conditions   = parsedJson['conditions'];
    extra_description   = parsedJson['extra_description'];
    speedasignment   = parsedJson['speedasignment'];
    surchargeassignment 	  = parsedJson['surchargeassignment'];
    sleepshift = parsedJson['sleepshift'];
    invoice = parsedJson['invoice'];
    client_payrate = parsedJson['client_payrate'];
    agreementtext = parsedJson['agreementtext'];
    agreement_id = parsedJson['agreement_id'];
    sleeptime   = parsedJson[' sleeptime'];
    preagreementtext   = parsedJson['preagreementtext'];
    year= parsedJson['year'];
    month = parsedJson['month'];
    day= parsedJson['day'];
    comment  = parsedJson['comment'];
    employee_id1  = parsedJson['employee_id1 '];
    employee_id2 = parsedJson['employee_id2'];
    employee_id3  = parsedJson['employee_id3 '];
    employee_id4  = parsedJson['employee_id4'];
    employee_id5 = parsedJson['employee_id5'];
    employee_id6 = parsedJson['employee_id6'];
    employee_id7 = parsedJson['employee_id7'];
    employee_id8 = parsedJson['employee_id8'];
    employee_id9 = parsedJson['employee_id9'];
    employee_id10 = parsedJson['employee_id10'];
    times_status= parsedJson['times_status'];
    times_id= parsedJson['times_id'];
    beforeinvoice_id= parsedJson['beforeinvoice_id'];
    admin_id= parsedJson['admin_id'];
    caninsertassignment= parsedJson['caninsertassignment'];
    breake= parsedJson['break'];
    totalclientpayrate= parsedJson['totalclientpayrate'];
    totalpayrate= parsedJson['totalpayrate'];
    duration= parsedJson['durationintime'];
    clientfirstname= parsedJson['clientfirstname'];
    clientlastname= parsedJson['clientlastname'];
    title= parsedJson['title'];
    emfirstname= parsedJson['emfirstname'];
    emlastname= parsedJson['emlastname'];
    maintime_from= parsedJson['maintime_from'];
    maintime_to= parsedJson['maintime_to'];
    company_name= parsedJson['company_name'];
    total= parsedJson['total'];
    temptotalpayrate= parsedJson['temptotalpayrate'];
    temptotalclientpayrate= parsedJson['temptotalclientpayrate'];
    temptotal= parsedJson['temptotal'];
  }
}
