//@dart=2.9
class Minvoice {
  int id;
  String status;
  int client_id;
  int department_id;
  int employee_id;
  String year ;
  String month;
  String day;
  String created_at;
  String registeras;
  String client_payrate;
  String type;
  String invoicenumber;
  String times_id;
  String logo;
  String company_name;
  String employee_name;
  String employee_email;
  String employee_addr;
  String employee_exteraaddr;
  String employee_city;
  String employee_phone;
  String kvk_number;
  String btw_number;
  String iban_number;
  String iban_holder;
  String department_title;
  String department_costsection;
  String employee_postalcode;
  String employeedeflogo;
  String clientfirstname;
  String clientlastname;
  String title;
  String emfirstname;
  String emlastname;
  String totalpayrate;
  String totalclientpayrate;
  String total;
  String temptotalpayrate;
  String temptotalclientpayrate;
  String temptotal;
  String totalinvoice;

  Minvoice.fromJson(Map<String , dynamic> parsedJson)
  {
    id= parsedJson['id'];
    status = parsedJson['status'];
    client_id = parsedJson['client_id'];
    department_id = parsedJson['department_id'];
    employee_id= parsedJson['employee_id'];
    year = parsedJson['year'];
    month = parsedJson['month'];
    day = parsedJson['day'];
    created_at = parsedJson['created_at'];
    registeras = parsedJson['registeras'];
    client_payrate = parsedJson['client_payrate'];
    type = parsedJson['type'];
    invoicenumber = parsedJson['invoicenumber'];
    times_id = parsedJson['times_id'];
    logo = parsedJson['logo'];
    company_name = parsedJson['company_name'];
    employee_name = parsedJson['employee_name'];
    employee_email = parsedJson['employee_email'];
    employee_addr = parsedJson['employee_addr'];
    employee_exteraaddr = parsedJson['employee_exteraaddr'];
    employee_city = parsedJson['employee_city'];
    employee_phone = parsedJson['employee_phone'];
    kvk_number = parsedJson['kvk_number'];
    btw_number = parsedJson['btw_number'];
    iban_number = parsedJson['iban_number'];
    iban_holder = parsedJson['iban_holder'];
    department_title = parsedJson['department_title'];
    department_costsection = parsedJson['department_costsection'];
    employee_postalcode = parsedJson['employee_postalcode'];
    employeedeflogo = parsedJson['employeedeflogo'];
    clientfirstname= parsedJson['clientfirstname'];
    clientlastname= parsedJson['clientlastname'];
    title= parsedJson['title'];
    emfirstname= parsedJson['emfirstname'];
    emlastname= parsedJson['emlastname'];
    totalclientpayrate= parsedJson['totalclientpayrate'];
    totalpayrate= parsedJson['totalpayrate'];
    total= parsedJson['total'];
    temptotalpayrate= parsedJson['temptotalpayrate'];
    temptotalclientpayrate= parsedJson['temptotalclientpayrate'];
    temptotal= parsedJson['temptotal'];
    totalinvoice= parsedJson['totalinvoice'];
  }
}
